### ISSUE TITLE
Handle previous and failed uploads for manuscript

### ISSUE THREAD

**Issue by erezmus** [libero/reviewer-submission#100]
Follow up from #55, we need to remove any previous manuscript. This can be done in two ways:

1) Like xpub do this during the `uploadManuscript mutation where it deletes current file with status 'MANUSCRIPT_SOURCE` and switches file with status 'MANUSCRIPT_SOURCE_PENDING' to 'MANUSCRIPT_SOURCE', effectively promoting pending file to current file
2) Add a `deleteManuscript` mutation that needs to be called by a client first and make the `uploadManuscript` throw an error if the submission currently has a manuscript

**Comment by erezmus** [comment]
I favour option 2) but needs checking with @hdrury1 and @chugginselifesciences that if an upload failure occurs when replacing a manuscript then no manuscript file is set as previous one is deleted.

**Comment by chugginselifesciences** [comment]
@erezmus If a second file upload fails it should remain in error state - no need to retrieve or keep the 1st file. I think that matches with what you've suggested so fine with me. Thanks

**Comment by norisalsaadie** [comment]
Closed by https://github.com/libero/reviewer-submission/pull/114
