### ISSUE TITLE
Fix FileUpload test

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer-submission#104]
For Norris

**Comment by norisalsaadie** [comment]
Testing using ApolloClient and ApolloClientUpload in a server environment is not so straight forward as the library relies on a browser context, as suspected. Though some end to end testing would be useful to ensure functionality works across browsers etc.

It makes sense to revert to using a simple HTTP library like fetch or axios. For now, I'll revert this single test upload test in question.
