### ISSUE TITLE
Tech Debt: Put user role in token

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer-submission#107]
In order to get the user's role currently we pass the "header" around which is a bit iky - see discussion.
ref: https://github.com/libero/reviewer-submission/pull/102#issuecomment-595124828

/cc @erezmus

**Comment by norisalsaadie** [comment]
In addition, consider adding JWKS to continuum adaptor and use key to verify token https://github.com/auth0/node-jwks-rsa
