### ISSUE TITLE
Create migration to add articleType to submissions table

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer-submission#31]
We need to create a migration so we have somewhere to store article type data. We had agreed to keep the postgres schema the same as xpubs initially to make migration easier. This data is nested in a meta data set in xpub so we'll need to decide how we approach this. Like for like schema or some improvements?

**Comment by Cooryd** [comment]
This can probably be closed once https://github.com/libero/reviewer/issues/535 is completed. may as well get whole schema migration done in one go.

**Comment by norisalsaadie** [comment]
As per @Cooryd comment. Closed.
