### ISSUE TITLE
Discussion: Do we keep using NestJS ?

### ISSUE THREAD

**Issue by erezmus** [libero/reviewer-submission#37]
## Background
We originally decided to use NestJS as it provides GraphQL out of the box as well as other "batteries included". However, we recently tried to add an Auth Guard for the GraphQL route and despite following the documentation couldn't make it work, making us wonder whether its still a good choice or whether we are better of opting with express as with the other services in libero reviewer.

## Arguments for keeping nestjs
* Offers the following out of the box(GraphQL, Security, Logging, Middleware, Guards, Authentication)
* Any others?

## Arguments for dropping nestjs
* Its hard to understand what is going on with the modules, services and decorators, so diagnosing issues like the one with the Auth Guard for graphql take a long time.
* There is seems to be quite a bit of a learning curve in learning how to use the framework and understanding its working.
* We don't need such a big framework for what we want to do.
* A lot of the features like security and authentication are provided by non NestJS packages that we could use directly

## If we drop NestJS, can we easily replace its features and how?
* We could use ExpressJS and same or similar packages that are used by NestJS
* For GraphQL, use apollo graphql server: https://www.apollographql.com/docs/apollo-server/v1/servers/express/
* Middleware and Auth Guards are easily implemented in ExpressJS
* Security, we can use `helmet` package (as NestJS does)
* Authentication: we can use `passportjs` package (as NestJS does)
* Logging: we can do the same as with other services and use `pino`.

## Is there anything we would not be easily able to replace if we moved away from NestJS?
* maybe task scheduling ? https://docs.nestjs.com/techniques/task-scheduling
* anything else?

## How long would it take to move to express ?
Erez: I estimate 1 day

**Comment by norisalsaadie** [comment]
Isn't this one now settled?

**Comment by erezmus** [comment]
only once its merged

**Comment by norisalsaadie** [comment]
Close by PR https://github.com/libero/reviewer-submission/pull/41
